##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile
##

all:
	cp pbrain-gomoku-ai.py pbrain-gomoku-ai
	chmod 777 pbrain-gomoku-ai

clean:
	rm pbrain-gomoku-ai

fclean:	clean

re:	clean fclean all
