##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## desc
##

SRC	=	my_revstr.c \
		my_strcpy.c \
		my_strlen.c \
		my_putchar.c \
		my_putstr.c \
		my_addition.c \
		my_char_cat.c \
		main.c

NAME =	infin_add

all:	compil

compil:
	gcc -o $(NAME) *.c

clean:
	rm -rf *.o

fclean:	clean

re:	fclean
	rm -rf $(NAME)